### ISSUE TITLE
Teams/Labels for APSIM Initiative Issues

### ISSUE THREAD

**Issue by sarahcleary** [APSIMInitiative/ReferencePanel#41]
As discussed in Sept. 2019 RP meeting - in order to facilitate APSIM users review/use of GitHub, the @APSIMInitiative/reference-panel will utilise the Label feature in GitHub.
Labels to be used:
winter cereals; Summer cereals; legumes; soils; livestock

Any others?

**Comment by Keith-Pembleton** [comment]
"Farm infrastructure" to cover things like dams, silage bunkers ect

**Comment by sno036** [comment]
forages; trees/shrubs; pests/diseases; 

Suggest rather than "Farm infrastructure" that use something like "farm-scale" to add in issues with multi-paddock management etc.

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - any further comment/input on "Labels" for GitHub Issues?  This is to facilitate APSIM users review and use of GitHub.

**Comment by kchenu** [comment]
Putting the crop species in addition could be good too if not too much additional work

**Comment by yashvirchauhan** [comment]
I agree with Karine, as frequently  issues raised may concern a particular crop species which may or may not be relevant to all crops.

**Comment by hol353** [comment]
I assume we're wanting to create these labels so that the long list of issues can be filtered. If so, then this filtering can already be done to an extent. You can include crop names in the filter box. For example, for wheat:
https://github.com/APSIMInitiative/ApsimX/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Ascience+wheat

You only get 17 items. This could be further refined. This approach looks for the word 'wheat' anywhere in the issue which means that there will be false positives.

Is this good enough? The alternative is we create 20 crop species labels that need to be applied manually by someone.

**Comment by sno036** [comment]
Wasn't the reason so that people could stay in touch with new science issues without getting ALL the GitHub emails? We talked about having large groupings of topics so that things didn't get too specific. Two options that I know about:

1. Labels prompt for filtering (but have to be applied manually) but I don't think you can subscribe to a Label so I am not sure they would assist with notifications.  

2. Team tags also need to be applied manually but they do send notifications to all in the team (e.g. "@APSIMInitiative/stock-and-related-matters" sends notifications to Dean, Neville, Mark and me (and easy to add more people).

Either way - too many options will not help matters and as @hol353 points out above, the filtering works quite well.

**Comment by hol353** [comment]
1. Setting up labels won't provide email notifications. They are applied manually but you can always save the filtered page as a bookmark which you can then quickly check once a week or so.
2. Yes, if you want notifications, then teams are what is needed.

I don't mind having a small set of labels for filtering. I also don't mind having teams. It really depends on what the RP want. I'll wait for clarification from the RP before implementing anything.

**Comment by Keith-Pembleton** [comment]
@HamishBrownPFR were the labels something to do with filtering in DevHub?  I looked back over the minutes where we decided to do this and it is associated with the DevHub discussion.

**Comment by sarahcleary** [comment]
As per discussion at RP meeting:   @APSIMInitiative/reference-panel to nominate teams  (max 5)

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - reminder.  
Refer to minutes from last meeting:  
Action:  Try max 5 teams initially. @APSIMInitiative/reference-panel to nominate teams in GitHub issue (by 11/10). Subscribe, join the teams you want.

**Comment by Keith-Pembleton** [comment]
RP in meeting suggests: Cereals, Legumes, other crops, soil, livestock and forages, pest and diseases. Feed back in 7 days please

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - any feedback?

**Comment by sarahcleary** [comment]
@hol353 - can you please set up these as 'teams' - Cereals, Legumes, other crops, soil, livestock and forages, pest and diseases 
thanks

**Comment by hol353** [comment]
Labels or teams?

**Comment by sarahcleary** [comment]
@hol353 - if you could set up both, that would be great.  The RP has decided that they would like to set up 'teams'.  Action from the last RP meeting was:  @APSIMInitiative/reference-panel to self nominate for teams and tag relevant issues

**Comment by hol353** [comment]
I have added the new teams and labels.

**Comment by sarahcleary** [comment]
Thanks @hol353  - how do you request to join a team?

**Comment by peter-devoil** [comment]
https://github.com/orgs/APSIMInitiative/teams.

**Comment by sarahcleary** [comment]
@hol353 - is the only way to request to join a team is to send you an email or put a request on this issue?  Doesn't seem to have a 'request to join' button on the link @peter-devoil has added above

**Comment by sarahcleary** [comment]
https://github.com/orgs/APSIMInitiative/teams - is up and running.  @APSIMInitiative/reference-panel - please join relevant teams.  Would be good for these to be used for discussion.

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - please note discussion and action from last RP meeting. If you haven't joined the relevant teams, please do.  Please note a number of teams have been tagged on issues.  Please either review, comment on these or commence a discussion.

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel  - as per previous dicussion and minutes - need to engage people into the discussion. Please join relevant teams and if possible, commence a 'team' discussion

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - as per previous dicussion and minutes - need to engage people into the discussion.  Please invite colleagues to join.
